name: sebastian_bot
description: A musically-oriented Telegram bot.
version: 1.0.0
repository: https://github.com/keenan-v1/sebastian-bot

environment:
  sdk: ^3.0.5

dependencies:
  ansicolor: ^2.0.1
  logging: ^1.2.0
  teledart: ^0.5.6
  yaml: ^3.1.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
